### ISSUE TITLE
Use SSH2

### ISSUE THREAD

**Issue by suhr** [pijul/pijul#1]

**Comment by P-E-Meunier** [comment]
Done already, libssh uses SSH2 by default.

**Comment by pijul** [comment]
Done already, libssh uses SSH2 by default.

**Comment by suhr** [comment]
Why don't use libssh2 then? It's much more widespread library.

**Comment by pijul** [comment]
Because (in decreasing priority order):
1. The authors of libssh2 use almost exclusively non-factual arguments (troll-type arguments) against libssh. It's not the spirit of the Pijul project, and if we ever have to interact with the authors of these libraries, we'd better agree on basic values such as mutual respect.
2. libssh2 doesn't seem to parse ~/.ssh/config.
3. ProxyCommand is not automatically handled in libssh2
4. libssh2 doesn't support building ssh servers.
5. The libssh documentation is easier to browse and read (doxygen-type doc).
6. libssh started in 2003, libssh2 seems to have started in 2009. Hence, libssh looks more stable.

Do you have any facts to back your claim that it's "more widespread".

**Comment by suhr** [comment]
I see. Well, sorry for troubling.

> Do you have any facts to back your claim that it's "more widespread".

Well, https://crates.io/search?q=ssh. Also looks like pijul is the only software that uses libssh in my system (gentoo).

**Comment by pijul** [comment]
Ooooh! you're talking about the crate. I started using it initially, and wrote a parse for ~/.ssh/config. Then I noticed ProxyCommands were not easy, and put on my todo list that bindings were needed. When I reached that line, someone had done it already, but for some reason did not appear in the crates.io search result.
Their crate is called "libssh".

**Comment by lowfatcomputing** [comment]
https://libssh2.org/libssh2-vs-libssh.html

In contrast to libssh, libssh2 aparently lacks support for a number of important things despite the 2 at the end, which seems to have fooled many people. (They are completely different projects)
